before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libdbus-1-dev
language: rust
cache: cargo
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
matrix:
    allow_failures:
        - rust: nightly
env:
- RUST_BACKTRACE=1
